### ISSUE TITLE
disable it with shortcut?

### ISSUE THREAD

**Issue by xverbatim1971** [nagi1999a/obsidian-focus-plugin#10] opened 2022-10-17 20:22 UTC
hi,
first thank you for this great plugin.

it helps me a lot in learning.

is there a possibility that another switch is built in?
I mean that you can completely disable it via a shortcut?
or a toggle function 1 x shortcut on/off.

would be perfect ;)

now it bothers me when i have your plugin on and i want to highlight and copy text easily, then i don't want to have a focus.
i hope you understand?

great work ... thanks

Translated with www.DeepL.com/Translator (free version)

**Comment by nagi1999a** [comment] 2022-10-19 01:48
Hello, @xverbatim1971 !
Thanks for your suggestion, it is a great idea! I will try to realize it in two weeks!

As a workaround for now, please try to adjust the [Focus Sensitivity](https://github.com/nagi1999a/obsidian-focus-plugin#focus-sensitivity) to avoid accidentally focus when mouse still.

**Comment by xverbatim1971** [comment] 2022-10-19 11:04
That would be really great :-)

Very helpful would be a switch. that you only need to assign a hotkey and this changes, then you can put this as a button in the sidebar (with commander) and conveniently turn on and off.

a dream :-)

Focus Sensitivity as a workaround - does not work so well!

thank you very much and thank you for the effort

**Comment by nagi1999a** [comment] 2022-10-19 12:47
I just released version 1.3 and include the feature.
Please try and leave a comment if it has any bugs, @xverbatim1971 !

After the update process(may need to restart Obsidian), you will see `Focus: on` area on the button-right corner or other position in the status bar, like the screenshot shows:
![Screenshot_20221019_204051](https://user-images.githubusercontent.com/49529145/196693554-c26b27c1-6885-4893-992a-24fd1930f779.png)

And the area is clickable! You can easily toggle the plugin on and off by clicking on it. Also, I have added a new command in the command palette called `Toggle Focus Mode`, which will do the same thing, but you can assign key binding with it.

Thanks again for providing such a great idea!

**Comment by xverbatim1971** [comment] 2022-10-19 13:46
I am speechless 👍 
that was very fast and I am very happy.
thank you for the good work.
it is going perfectly so far.

thanks again for the effort 
all the best
--
**_another idea/suggestion_** 

about the statusbar function - it might be helpful if you can turn it on or off in the plugin settings.
the feedback is good in the statusbar.
i personally don't really need it. i have an icon at the top of the header to trigger the function. i can see when the text is hidden - it's on. if the text is completely displayed - it is off.

but that's not really a problem.

maybe an option? one likes it with status, another not :-)

thanks again 

best regards
Thomas

**Comment by nagi1999a** [comment] 2022-10-19 14:34
Big thanks for the suggestion again!
I have released version 1.3.1, which includes a new option to disable the indicator in the settings tab. Please try it out!

**Comment by nagi1999a** [comment] 2022-11-16 05:26
Looks like the feature is working! I am going to close the issue, if there is any unexpected behavior, please feel free to leave a comment!

**Closed by nagi1999a** 2022-11-16 05:26 UTC
Labels: enhancement, Testing
